steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "--build-arg"
      - "DATABASE_URL=$$DATABASE_URL"
      - "--build-arg"
      - "BUILDKIT_INLINE_CACHE=1"
      - "--cache-from"
      - "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:latest"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:latest"
      - "."
    secretEnv: ["DATABASE_URL"]

  # Step 2: Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - "push"
      - "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"

  # Step 3: Run database migrations
  # - name: "gcr.io/google-appengine/exec-wrapper"
  #   id: "migrate-db"
  #   entrypoint: "bash"
  #   args:
  #     - "-c"
  #     - "/buildstep/execute.sh -i asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID -s ${_CLOUD_SQL_INSTANCE} -e DATABASE_URL=$$MIGRATE_DB_URL -- npx prisma@6.19.0 migrate deploy"
  #   secretEnv: ["MIGRATE_DB_URL"]
  - name: "node:20"
    id: "migrate-db"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "================ DEBUG START ================"

        # 1. ติดตั้ง Proxy
        echo "[1] Installing Cloud SQL Proxy..."
        wget -q https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy

        # 2. รัน Proxy (TCP Mode)
        echo "[2] Starting Proxy on 127.0.0.1:5432..."
        ./cloud_sql_proxy -instances=${_CLOUD_SQL_INSTANCE}=tcp:5432 &
        PROXY_PID=$$!  # <-- แก้เป็น $$! (Process ID)

        echo "Waiting for proxy to stabilize (5s)..."
        sleep 5

        # 3. เตรียม URL
        echo "[3] Preparing Connection String..."

        # ใช้ $$ นำหน้าตัวแปร Env และตัวแปร Shell ทั้งหมด
        if [ -z "$$MIGRATE_DB_URL" ]; then
           echo "❌ ERROR: MIGRATE_DB_URL is empty!"
           exit 1
        fi

        # แปลง URL
        export DATABASE_URL=$(echo $$MIGRATE_DB_URL | sed -E 's/@[^:]+:[0-9]+/@127.0.0.1:5432/')

        # ปริ้นเช็ค (เซ็นเซอร์รหัสผ่าน)
        # แก้ $SAFE_URL เป็น $$SAFE_URL
        SAFE_URL=$(echo $$DATABASE_URL | sed -E 's/:[^@]+@/:****@/')
        echo "✅ Target URL: $$SAFE_URL"

        # 4. ทดสอบ Connection
        echo "[4] Checking Port Connectivity..."
        if nc -z 127.0.0.1 5432; then
            echo "✅ Connectivity OK: Port 5432 is open."
        else
            echo "❌ Connectivity FAIL: Cannot reach 127.0.0.1:5432. Proxy might be dead."
            ps aux | grep cloud_sql_proxy
        fi

        echo "================ STARTING PRISMA ================"

        # 5. รันคำสั่งจริง
        npx prisma@6.19.0 migrate deploy

        # เก็บ Exit Code ไว้เช็คตอนจบ
        EXIT_CODE=$$? # <-- แก้เป็น $$?

        # 6. เก็บกวาด (Kill Proxy)
        kill $$PROXY_PID # <-- แก้เป็น $$PROXY_PID

        if [ $$EXIT_CODE -eq 0 ]; then
            echo "✅ MIGRATION SUCCESS"
        else
            echo "❌ MIGRATION FAILED (Exit Code: $$EXIT_CODE)"
            exit $$EXIT_CODE
        fi

    # อย่าลืมเรียกตัวแปร Secret เข้ามา
    secretEnv: ["MIGRATE_DB_URL"]

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloudrun"
    args:
      - "run"
      - "deploy"
      - "primary-advantage-app"
      - "--image=asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"
      - "--region=asia-southeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--set-secrets=DATABASE_URL=${_DATABASE_URL}:21"
      - "--set-secrets=RESEND_API_KEY=${_RESEND_API_KEY}:latest"
      - "--set-secrets=AUTH_SECRET=${_AUTH_SECRET}:latest"
      - "--set-secrets=AUTH_URL=${_AUTH_URL}:latest"
      - "--set-secrets=AUTH_GOOGLE_ID=${_AUTH_GOOGLE_ID}:latest"
      - "--set-secrets=AUTH_GOOGLE_SECRET=${_AUTH_GOOGLE_SECRET}:latest"
      - "--set-secrets=OPENAI_API_KEY=${_OPENAI_API_KEY}:latest"
      - "--set-secrets=VERTEX_CLIENT_EMAIL=${_VERTEX_CLIENT_EMAIL}:latest"
      - "--set-secrets=VERTEX_PRIVATE_KEY=${_VERTEX_PRIVATE_KEY}:latest"
      - "--set-secrets=GOOGLE_API_KEY=${_GOOGLE_API_KEY}:latest"
      - "--set-secrets=AUDIO_API_KEY=${_AUDIO_API_KEY}:latest"
      - "--set-secrets=STORAGE_BUCKET_NAME=${_STORAGE_BUCKET_NAME}:latest"
      - "--set-secrets=STORAGE_CLIENT_EMAIL=${_STORAGE_CLIENT_EMAIL}:latest"
      - "--set-secrets=STORAGE_PRIVATE_KEY=${_STORAGE_PRIVATE_KEY}:latest"
      - "--set-env-vars=PROJECT_ID=${_PROJECT_ID}"
      - "--set-env-vars=NODE_ENV=${_NODE_ENV}"
      - "--set-env-vars=AUTH_TRUST_HOST=true"
      - "--set-env-vars=ACCESS_KEY=${_ACCESS_KEY}"

# Substitutions
substitutions:
  _NODE_ENV: "production"
  _PROJECT_ID: "primary-advantage"
  _DATABASE_URL: "DATABASE_URL"
  _RESEND_API_KEY: "RESEND_API_KEY"
  _AUTH_SECRET: "AUTH_SECRET"
  _AUTH_URL: "AUTH_URL"
  _AUTH_GOOGLE_ID: "AUTH_GOOGLE_ID"
  _AUTH_GOOGLE_SECRET: "AUTH_GOOGLE_SECRET"
  _OPENAI_API_KEY: "OPENAI_API_KEY"
  _VERTEX_CLIENT_EMAIL: "VERTEX_CLIENT_EMAIL"
  _VERTEX_PRIVATE_KEY: "VERTEX_PRIVATE_KEY"
  _GOOGLE_API_KEY: "GOOGLE_API_KEY"
  _AUDIO_API_KEY: "AUDIO_API_KEY"
  _STORAGE_BUCKET_NAME: "STORAGE_BUCKET_NAME"
  _STORAGE_CLIENT_EMAIL: "STORAGE_CLIENT_EMAIL"
  _STORAGE_PRIVATE_KEY: "STORAGE_PRIVATE_KEY"
  _ACCESS_KEY: "ACCESS_KEY"
  _CLOUD_SQL_INSTANCE: "reading-advantage:asia-southeast1:cloud-sql"

# Secrets
availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/${_DATABASE_URL}/versions/21
      env: "DATABASE_URL"
    - versionName: projects/${_PROJECT_ID}/secrets/${_DATABASE_URL}/versions/latest
      env: "MIGRATE_DB_URL"

options:
  logging: CLOUD_LOGGING_ONLY
