steps:
  # Step 1: Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "build-image"
    args:
      - "build"
      - "-t"
      - "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"
      - "."
      - "--build-arg=DATABASE_URL=${_DATABASE_URL}"
    secretEnv: ["DATABASE_URL"]

  # Step 2: Push Docker image
  - name: "gcr.io/cloud-builders/docker"
    id: "push-image"
    args:
      - "push"
      - "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"

  # Step 3: Run database migrations
  - name: "asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"
    id: "migrate-database"
    entrypoint: "npx"
    args:
      - "-c"
      - |
        if [ "${_SKIP_MIGRATIONS}" = "true" ]; then
          echo "Skipping database migrations"
          exit 0
        fi
        npx prisma migrate deploy
    # args: ["prisma", "migrate", "deploy"]
    secretEnv: ["DATABASE_URL"]

  # Step 4: Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    id: "deploy-cloudrun"
    args:
      - "run"
      - "deploy"
      - "primary-advantage-app"
      - "--image=asia-southeast1-docker.pkg.dev/${_PROJECT_ID}/primary-advantage-repo/primary-advantage-app:$BUILD_ID"
      - "--region=asia-southeast1"
      - "--platform=managed"
      - "--allow-unauthenticated"
      - "--set-secrets=DATABASE_URL=${_DATABASE_URL}:latest,RESEND_API_KEY=${_RESEND_API_KEY}:latest"

# Substitutions
substitutions:
  _PROJECT_ID: "primary-advantage"
  _DATABASE_URL: "DATABASE_URL"
  _RESEND_API_KEY: "RESEND_API_KEY"

# Secrets
availableSecrets:
  secretManager:
    - versionName: projects/${_PROJECT_ID}/secrets/${_DATABASE_URL}/versions/latest
      env: "DATABASE_URL"

options:
  logging: CLOUD_LOGGING_ONLY
